### ISSUE TITLE
Some examples fail

### ISSUE THREAD

**Issue by raff** [spy16/parens#1]
simple.lisp and threading_macros.lisp fail with the error "error: first argument must be list of symbols, not 'parser.ListExpr'". The problem seems to be the use of (params) instead of [params] in defn or lambda.

**Comment by spy16** [comment]
Thanks for reporting. I changed the synatax of `lambda` and `defn` params from `(params...)` to `[params...]` and forgot to change the samples. I have fixed the samples now. Will be adding unit tests to cover these as well.
