### ISSUE TITLE
Archiving Parens

### ISSUE THREAD

**Issue by spy16** [spy16/parens#10]
I am thinking of archiving this repo (and may be eventually remove) in favour of [Sabre](https://github.com/spy16/sabre). Sabre reader & evaluation logic is mostly complete and is much better than Parens. (For example, reader is much flexible. Everything including reader forms and values are represented using a `Value` type which is more closer to LISP. Invocation of a value is unified using a `Invokable` optional interface which allows for example implementing Clojure like index-access on Vectors; i.e., `([1 2 3 4] 0)` returns `1`. Also has support for `Set`. A Clojure-like hash-map can also be added without touching sabre code base.)

@lthibault

**Comment by lthibault** [comment]
Sounds good to me.  Would you be open to having an extra collaborator working on Sabre?  I'd be interested in e.g. taking care of documentation.  I'm building a project around this and would be happy to provide some feedback from the trenches.

**Comment by spy16** [comment]
I'd be happy to have a collaborator. I have added you.

**Comment by lthibault** [comment]
Thanks -- looking forward to seeing where this goes :)
