### ISSUE TITLE
Implement `reader` package

### ISSUE THREAD

**Issue by spy16** [spy16/parens#13]
- [x] Implement `Reader` with macro-table + dispatch-table. (Mostly take from Sabre)
- [x] Implement `New()` with functional options to customise all internal tables, number-reader.
- [x] Implement `WithMacroTable`, `WithDispatchTable`, `WithNumberReader` etc. 

```go
type Reader interface {
    All() ([]Any, error)
    One() (Any, error)
}
```

**Comment by lthibault** [comment]
Any particular reason `Reader` is now an interface?

**Comment by spy16** [comment]
Oh no reader will not be an interface. I was just indicating the high level signatures it would have.

**Comment by lthibault** [comment]
See #19.  `WithNumberReader` still needs implementing.
