### ISSUE TITLE
Use pointer receiver when you want to modify

### ISSUE THREAD

**Issue by twoi** [spy16/parens#3]
I stumbled upon your library and I like it! It may prevent me from reinventing the (lisp) wheel in go.

However, you should change all methods that modify their "this" instance, like the following one, to use pointer receivers, otherwise assignments like below `ne.Number = ...` amount to no-ops.

```
func (ne NumberExpr) Eval(scope Scope) (interface{}, error) {
	if ne.Number == nil {
		num, err := strconv.ParseFloat(ne.NumStr, 64)
		if err != nil {
			return nil, err
		}

		ne.Number = num
	}

	return ne.Number, nil
}
```

**Comment by spy16** [comment]
That seems to be a bug. Initially all expr implementations were using value receivers. The `ne.Number` was added later to avoid calling `strconv.Atoi` everytime the value is used. But looks like I forgot to change it to pointer receiver. Thanks for the issue. Will fix it.

**Comment by spy16** [comment]
I have fixed this by removing the number caching for now (which was in-effective so far anyway due to the value-receiver)
