### ISSUE TITLE
proxy golang stale cache

### ISSUE THREAD

**Issue by spy16** [spy16/parens#30]
@lthibault I was looking at <https://pkg.go.dev/github.com/spy16/parens> today and realized it is still showing the old Parens releases which don't exist anymore.  Also, after discussion on Gophers slack, I came to know that it's not possible to update that  anymore. I don't know what do about this. The cleanest and the right thing to do would be move to a new repository with different name 😔 .. But we have changed this way too many times already. any thoughts?

**Comment by lthibault** [comment]
Yikes, that's a pain.  As far as I know we don't have many (any?) active users, so we might be able to get away with a rename.  It seems like the cleanest option to me.

The other option I see (unless I'm overlooking something that prevents it) is [creating a v2](https://blog.golang.org/v2-go-modules) of parens.  Here are the problems I see:

1. Adding a `/v2` suffix to the go module's import path breaks installations that rely on $GOPATH.
2. Adding a `/v2` source directory is horrifyingly ugly, and makes the codebase less inviting to contributors.
3. We already squashed the previous commit history, so we'll have a v2 without a v1, which might make things confusing to users.

All things considered, I'm in favor of biting the proverbial bullet and moving to a new repository.  In fact, I suggest taking this opportunity to move the project to its own github organization.  The name `parenz` seems to be available, and I quite like it.

**Comment by spy16** [comment]
I like `parenz`. We can go with that (Although, If a fancier name comes to your mind, do recommend. something that we can add a logo easily as well  😄 ). Sorry, But I am not entirely convinced on the GitHub organization approach though. Just to be clear, it's not a desire to keep the project under my GitHub account or anything like that😅. I consider this project to be a simple and useful library others can use in a large project (like Cobra, Viper etc.) but organization sounds like this itself is a large standalone project. Does that make sense to you ?

**Comment by lthibault** [comment]
Makes perfect sense!  And don't worry, I totally understand where you're coming from.

Frankly, I'm glad we're able to push back against each other's ideas.  It's an essential part of working together, and your inclination to keep things simple has stood us in good stead.

Regarding a fancier name, here are a few ideas floating around in the old 🧠:

- `slurp`  (It kinda reminds me of "lisp", phonetically.  Also evokes the reader slurping up forms.)
- `ligo` (**li**sp + **go**.  The name conflicts with the somewhat famous [LIGO](https://www.ligo.caltech.edu/) group, but we might not care.)
- `marmot`([Marmots](https://en.wikipedia.org/wiki/Marmot) are close relatives of gophers.)
- `formite` (A portmanteau of "form" and "fomite".  The name came from the idea of "infecting" gophers with lisp. It's topical, if a bit tasteless...)

And my last idea is simply:  `phil`.  Let me explain.

In the region where I grew up, there's a [silly tradition](https://en.wikipedia.org/wiki/Punxsutawney_Phil) of asking a groundhog -- named Phil -- whether or not Spring has arrived.  Groundhogs somehow strike me as an older, wiser gophers, which calls to mind the meme of older, wiser programmers (re)discovering lisp.  If we go with this one, the mascot and logo become pretty obvious! 😆 

Of these, my favorites are `slurp` and `phil`.  They're short, memorable, and unlikely to clash with other package names.

Thoughts?

(P.S.:  naming things is fun.)

**Comment by spy16** [comment]
Those are some really nice names. I think personally I like the names in this order:

1. ligo ( is an abbreviation combining lisp and go. And sounds like LEGO which is kinda what the project is about - small pieces that can be composed)
2. slurp (sounds really cool and is a fairly well known lisp function I think). 
3. phil (short and sweet, has a nice story behind it and logo would be easy I guess. Only reason why it's last item in the list is because it feels arbitrary without the story). 

I am okay with slurp or ligo. ( I don't think using ligo will be a big problem since the other LIGO is not a software project ).

**Comment by lthibault** [comment]
Shall we go with `slurp`, then?

**Comment by spy16** [comment]
Yea sure. I will create the repository and move stuff over. Here we go again! 😄 (Kinda unfortunate that we will lose all the stars 😅 )
