### ISSUE TITLE
Allow users to add custom atoms

### ISSUE THREAD

**Issue by lthibault** [spy16/parens#4]
Hello,

I've started using parens for a project of mine, and have encountered the need to define my own atoms.   In particular, I would like expressions resembling `/this/is/a/path` to evaluate to a `PathExpr` type.

I've made the necessary changes [in my own branch](https://github.com/spy16/parens/compare/master...lthibault:master), and was wondering if there was any interest in merging this in?

If so, I'm happy to submit a PR.

Here's an example of how to use this feature.  I've tried to stay close to paren's design.  Note that `parens.Parse` take variadic arguments, to preserve backwards-compatibility.

```go
parens.Parse("(somePathFunc /some/path/expr )", MatchPath{})
```

**Comment by spy16** [comment]
Hi!. Thanks for using Parens and for the issue!

I did have a similar idea initially (A *parser engine* that can be customized in every aspect including different syntactical features in the interest of making it highly flexible scripting engine). But didn't get the time to pull it off. 

I like the `Matcher` idea that you have implemented. Please do send a PR.

**Comment by lthibault** [comment]
Hello,

Wonderful!  I'm happy this PR is appreciated upstream 😃 

By the way, I found this library to be a pleasure to use.  Thanks for making it!

**Comment by lthibault** [comment]
P.S.:  If your parser engine project ever gets started, please let me know.  I'd be interested in something like this.

**Comment by spy16** [comment]
Will merge today sometime. Thanks :)

**Comment by spy16** [comment]
> P.S.: If your parser engine project ever gets started, please let me know. I'd be interested in something like this.

Definitely ! Out of curiosity, do you have any specific expectations from such an engine?. My idea was to have generic tokenizer that understands only certain tokens like `(`, `)`, `[` and so on. and parser that consumes the token stream based on what features are enabled and builds an AST (same way parens does). I didn't really have an end goal here, just knew this would be a fun thing to do!  😃

**Comment by lthibault** [comment]
>Will merge today sometime. Thanks :)

Great! Thanks!

>[...] do you have any specific expectations [...] I didn't really have an end goal here, just knew this would be a fun thing to do! 😃

In a word, I'm looking for something very flexible that will allow me to develop and test new syntax very quickly.  I'm not at all concerned with performance at this stage. 

I'm quite new to language design, so I'm ideally looking for something at a similar level of abstraction as `parens`.  I ended up using parens because it was a very thin layer on top of a language I already know, and I felt comfortable diving into the code when something was missing (e.g. this issue).

Hope this helps!

**Comment by spy16** [comment]
PR has been merged. Closing this issue.

**Comment by spy16** [comment]
@lthibault I was working with clojure recently. Looked at clojure language codebase and got some interesting ideas. Implemented what I think is much flexible and much better parser: https://github.com/spy16/sabre (execution is still not complete. I'm just learning some clojure concepts and might make lot of changes. But if you're interested you can take a look at the reader)

**Comment by lthibault** [comment]
@spy16 Ha! Excellent timing!  I've actually been digging into closure as well.  I'll check this out when I get a chance (probably this weekend).

Thanks for letting me know!

**Comment by lthibault** [comment]
@spy16 Quick question:  how would I go about implementing something similar to https://github.com/spy16/parens/issues/4 in Sabre?

**Comment by spy16** [comment]
Sabre uses the following steps to read forms:

1. If initial characters in the stream start with 0-9 or +/-, try to read a number.
2. If step 1 is not a match, lookup the first character in the stream in the read-table to see if there is a reader macro available.  If available, hand over the stream to the macro. (For example: If stream has `"` at the beginning, the default read table has a reader macro `readString`).
3. If step 2 is not a match, read the characters into a symbol until a terminal character is reached.

So, one way to handle the #4 in Sabre would be to add a custom reader macro that is triggered by a character. For example let's say you want to add support for Unix-like paths (i.e., starting with `/`).

1. Write a reader macro and optionally a custom `Path` form type.

```go
func readUnixPath(rd *sabre.Reader, init rune) (sabre.Form, error) {
	var path strings.Builder
	path.WriteRune(init)

	for {
		r, err := rd.NextRune()
		if err != nil {
			if err == io.EOF {
				break
			}

			return nil, err
		}

		if rd.IsTerminal(r) && r != '/' {
			break
		}

		path.WriteRune(r)
	}

	return Path(path.String()), nil
}

type Path string

func (p Path) Eval(_ sabre.Scope) (sabre.Value, error) {
	return string(p), nil
}
```

2. Then register with the reader

```go
rd := sabre.New(...)
rd.SetMacro('/', readUnixPath)
```
